apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-build-multiarch
spec:
  tasks:
    - name: init
      params:
        - name: image-url
          value: $(params.output-image)

        - name: rebuild
          value: $(params.rebuild)

        - name: skip-checks
          value: $(params.skip-checks)
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: init

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:092c113b614f6551113f17605ae9cb7e822aa704d07f0e37ed209da23ce392cc

          - name: kind
            value: task

    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)

        - name: revision
          value: $(params.revision)

        - name: ociStorage
          value: $(params.output-image).git

        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)
      runAfter:
        - init
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: git-clone-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:d1e63ec00bed1c9f0f571fa76b4da570be49a7c255c610544a461495230ba1b1

          - name: kind
            value: task
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: basic-auth
          workspace: git-auth

    - name: prefetch-dependencies
      params:
        - name: input
          value: $(params.prefetch-input)

        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)

        - name: ociStorage
          value: $(params.output-image).prefetch

        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)
      runAfter:
        - clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: prefetch-dependencies-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.1@sha256:621b13ab4a01a366a2b1d8403cf06b2b7418afd926d13678c4432858514407d3

          - name: kind
            value: task
      workspaces:
        - name: git-basic-auth
          workspace: git-auth

        - name: netrc
          workspace: netrc

    - name: get-version
      params:
        - name: source_artifact
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      taskRef:
        name: get-version

    - name: build-image
      displayName: "build-image-$(params.PLATFORM)"
      matrix:
        params:
          - name: PLATFORM
            value:
              - $(params.build-platforms)
      params:
        - name: IMAGE
          value: $(params.output-image)

        - name: DOCKERFILE
          value: $(params.dockerfile)

        - name: CONTEXT
          value: $(params.path-context)

        - name: HERMETIC
          value: $(params.hermetic)

        - name: PREFETCH_INPUT
          value: $(params.prefetch-input)

        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)

        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)

        - name: BUILD_ARGS
          value:
            - $(params.build-args[*])
            - VERSION=$(tasks.get-version.results.version)

        - name: BUILD_ARGS_FILE
          value: $(params.build-args-file)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)

        - name: IMAGE_APPEND_PLATFORM
          value: "true"
      runAfter:
        - prefetch-dependencies
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: buildah-remote-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.2@sha256:bd704cf7eb042f1fd48bfbd872a3f5a3632697a117602e242653ed323e6db52e

          - name: kind
            value: task
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"

    - name: build-image-manifest
      params:
        - name: IMAGE
          value: $(params.output-image)

        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)

        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)

        - name: ALWAYS_BUILD_INDEX
          value: $(params.build-image-manifest)

        - name: IMAGES
          value:
            - $(tasks.build-image.results.IMAGE_REF[*])
      runAfter:
        - build-image
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: build-image-index

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.1@sha256:327d745a58c1589b0ff196ed526d12a8a0a20ae22fd1c9dd1577b850a977dc3b

          - name: kind
            value: task
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"

    - name: deprecated-base-image-check
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-manifest.results.IMAGE_URL)

        - name: IMAGE_DIGEST
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: deprecated-image-check

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.4@sha256:b4f9599f5770ea2e6e4d031224ccc932164c1ecde7f85f68e16e99c98d754003

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: clair-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clair-scan

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.2@sha256:28fee4bf5da87f2388c973d9336086749cad8436003f9a514e22ac99735e056b

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: ecosystem-cert-preflight-checks
      params:
        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: ecosystem-cert-preflight-checks

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.1@sha256:5131cce0f93d0b728c7bcc0d6cee4c61d4c9f67c6d619c627e41e3c9775b497d

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: sast-snyk-check
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: sast-snyk-check-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.3@sha256:92af5ba1bb9d6bf442c8d3b317ada71d44a9c1ab59959a37bbb5d163205a104f

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: clamav-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clamav-scan

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.1@sha256:a94b6523ba0b691dc276e37594321c2eff3594d2753014e5c920803b47627df1

          - name: kind
            value: task
      when:
        - input: "{{ event_type }}"
          operator: in
          values:
            - "push"

    - name: apply-tags
      params:
        - name: IMAGE
          value: $(tasks.build-image-manifest.results.IMAGE_URL)

        - name: ADDITIONAL_TAGS
          value:
            - $(params.tag-prefix)$(tasks.clone-repository.results.short-commit)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: apply-tags

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.1@sha256:f485e250fb060060892b633c495a3d7e38de1ec105ae1be48608b0401530ab2c

          - name: kind
            value: task

    - name: push-dockerfile
      params:
        - name: IMAGE
          value: $(tasks.build-image-manifest.results.IMAGE_URL)

        - name: IMAGE_DIGEST
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: DOCKERFILE
          value: $(params.dockerfile)

        - name: CONTEXT
          value: $(params.path-context)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: push-dockerfile-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-push-dockerfile-oci-ta:0.1@sha256:e32feb2c815116730917fe5665d9f003e53f2e1718f60bcbabf0ab3abad5d7d4

          - name: kind
            value: task

    - name: rpms-signature-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: rpms-signature-scan

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-rpms-signature-scan:0.2@sha256:b627a8040f900bf359b50bfb5201907f73712ae5949270d57ea30cff11df078c

          - name: kind
            value: task

  params:
    - name: git-url
      description: Source Repository URL
      type: string

    - name: revision
      description: Revision of the Source Repository
      type: string
      default: ""

    - name: output-image
      description: Fully Qualified Output Image
      type: string

    - name: path-context
      description: Path to the source code of an application's component from where to build image.
      type: string
      default: .

    - name: dockerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
      type: string
      default: Dockerfile

    - name: rebuild
      description: Force rebuild image
      type: string
      default: "false"

    - name: skip-checks
      description: Skip checks against built image
      type: string
      default: "false"

    - name: hermetic
      description: Execute the build with network isolation
      type: string
      default: "false"

    - name: prefetch-input
      description: Build dependencies to be prefetched by Cachi2
      type: string
      default: ""

    - name: image-expires-after
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      default: ""

    - name: build-source-image
      description: Build a source image.
      type: string
      default: "false"

    - name: build-image-manifest
      description: Add built image into an OCI image index
      type: string
      default: "true"

    - name: build-args
      type: array
      description: Array of --build-arg values ("arg=value" strings) for buildah
      default: []

    - name: build-args-file
      description: Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah-build#--build-arg-file
      type: string
      default: ""

    - name: build-platforms
      description: List of platforms to build the container images on. The available set of values is determined by the configuration of the multi-platform-controller.
      type: array
      default:
        - linux/x86_64
        - linux/arm64

    - name: tag-prefix
      description: Prefix added to additional tags
      type: string
      default: ""

  workspaces:
    - name: git-auth
      optional: true

    - name: netrc
      optional: true

  results:
    - name: IMAGE_URL
      description: ""
      value: $(tasks.build-image-manifest.results.IMAGE_URL)

    - name: IMAGE_DIGEST
      description: ""
      value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

    - name: CHAINS-GIT_URL
      description: ""
      value: $(tasks.clone-repository.results.url)

    - name: CHAINS-GIT_COMMIT
      description: ""
      value: $(tasks.clone-repository.results.commit)


  finally:
    - name: show-sbom
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: show-sbom

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:52f8b96b96ce4203d4b74d850a85f963125bf8eef0683ea5acdd80818d335a28

          - name: kind
            value: task

