apiVersion: tekton.dev/v1
kind: Task
metadata:
  namespace: cost-mgmt-dev-tenant
  name: get-version

spec:
  description: Get version number
  params:
    - name: source_artifact
      description: The Trusted Artifact URI pointing to the artifact with the application source code.
      type: string

  results:
    - name: version_tag
      description: Image tag used for release version

  volumes:
    - name: workdir
      emptyDir: {}

  stepTemplate:
    volumeMounts:
      - name: workdir
        mountPath: /var/workdir

  steps:
    - name: use-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:a390d28f69d61ab38aadf78b7c9b21ed09b79687bddae4cf1d02616bef5d7da7
      args:
        - use
        - $(params.source_artifact)=/var/workdir/source

    - name: determine-image-tag
      image: registry.access.redhat.com/ubi9:latest
      workingDir: /var/workdir/source
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        image_tag="$(./get_image_tag.sh)"
        echo -n "$image_tag" | tee "$(results.version_tag.path)"
